version: '3.8'

services:
  app:
    image: po:latest
    restart: always
    environment:
      DB_HOST: e-commerce-database-1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: evershop
      DB_SSLMODE: disable
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - evershop-network

  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evershop
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - evershop-network

networks:
  evershop-network:
    driver: bridge

volumes:
  postgres-data:
